<xml>
    <pragma once="true"/>

    <set name="dough_include" value="${haxelib:dough}/src/native"/>
    <set name="sdl3_path" value="${haxelib:dough}/libs"/>
    <set name="sdl3_include" value="${sdl3_path}/SDL/include"/>
    <set name="sdl3_lib" value="${haxelib:dough}/build/libs/SDL"/>

    <section>
        <files id="haxe">
            <compilerflag value="-I${sdl3_include}"/>
            <compilerflag value="-I${dough_include}"/>
        </files>

        <files id="__main__">
            <compilerflag value="-I${dough_include}"/>
            <compilerflag value="-I${sdl3_include}"/>
        </files>

        <files id="__lib__">
            <compilerflag value="-I${sdl3_include}"/>
            <compilerflag value="-I${dough_include}"/>
        </files>

        <target id="haxe" tool="linker" toolid="exe" if="windows">
            <compilerflag value="-I${sdl3_include}"/>
            <compilerflag value="-I${dough_include}"/>

            <lib name="${sdl3_lib}/SDL3.dll"/>

            <lib name="winmm.lib"/>
            <lib name="gdi32.lib"/>
            <lib name="user32.lib"/>
            <lib name="ole32.lib"/>
            <lib name="oleaut32.lib"/>
            <lib name="shell32.lib"/>
            <lib name="advapi32.lib"/>
            <lib name="setupapi.lib"/>
            <lib name="imm32.lib"/>
            <lib name="cfgmgr32.lib"/>
            <lib name="version.lib"/>
        </target>

        <target id="haxe" if="linux">
            <compilerflag value="-I${sdl3_include}"/>
            <compilerflag value="-I${dough_include}"/>

            <lib name="-L${sdl3_lib}"/>
            <lib name="-lSDL3"/>

            <lib name="-ldl"/>
            <lib name="-lpthread"/>
            <lib name="-lm"/>
        </target>

        <target id="haxe" if="android">
            <lib name="-L${sdl3_lib_android}"/>
            <lib name="-lSDL3"/>

            <lib name="-llog"/>
            <lib name="-landroid"/>
            <lib name="-lEGL"/>
            <lib name="-lGLESv3"/>
            <lib name="-lOpenSLES"/>
        </target>
    </section>
</xml>
